server:
  port: 8088
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://mysql:3306/smart_slot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 30000
      pool-name: SmartSlotProdHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 生产环境关闭详细控制台 SQL 日志输出以获得极致性能
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

knife4j:
  # 生产环境安全合规：可按需关闭开放文档
  enable: false
